Use the v7 prerelease of AXElements for now
The newer version of the mouse gem that it depends on seems to take care
of this silliness that was happening in Yosemite + Chef Omnibus:

mouser.c:73:11: error: using integer absolute value function 'abs' when
argument is of floating point type [-Werror,-Wabsolute-value]
while (!CLOSE_ENOUGH(current_point, end_point)) {
mouser.c:22:55: note: expanded from macro 'CLOSE_ENOUGH'
define CLOSE_ENOUGH(a,b) ((abs(a.x - b.x) < 1.0) && (abs(a.y - b.y) < 1.0))
mouser.c:73:11: note: use function 'fabs' instead